### PR TITLE
Add Awesome repository to category tool

### PR DESCRIPTION
**Pull request by thomasbnt**
- [Link to the official Awesome repository](https://github.com/sindresorhus/awesome)
- [Link to the **Awesome Web Monetization repository**](https://github.com/thomasbnt/awesome-web-monetization)

### CODE REVIEW

**Comment by sharafian** [comment]
That list is great! I'm not sure how well it fits into 'tools' though; we could put it there in a pinch but maybe it should be in more of a reference/community section? @adrianhopebailie what do you think?

**Comment by thomasbnt** [comment]
@sharafian Even I didn't know where to put it ^^

**Comment by adrianhopebailie** [comment]
Yeh, I was thinking the same but also not sure where to put it. I'll add a new section for "Resources" and move it there.
@thomasbnt can you complete the IPR commitment in the interim.

**Comment by adrianhopebailie** [comment]
@thomasbnt I've moved your link to the resources section WDYT?

**Comment by thomasbnt** [comment]
Can't check IPR action, when I go to the website, I can't load PR information when I'm connected

**Pull request merged**
