### PR TITLE
Correct spelling in footer

### PR DESCRIPTION
**Pull request by edent**
Fix typo

### CODE REVIEW

**Comment by sidvishnoi** [comment]
This one maybe intentional due to https://www.forem.com/ which the community forum uses 😄

**Comment by edent** [comment]
Sure, but you wouldn't say "Visit our WordPress" or "Click here for our phpBB" would you?

Relying on users knowing exactly what obscure software runs your systems doesn't seem sensible to me.

**Comment by huijing** [comment]
Hello, we'd like to make an alternative suggestion of naming the link "Community" instead, sidestepping this odd forem/forum issue altogether.

**Comment by ioana-chiorean** [comment]
@edent Thanks so much for your contribution!

**Pull request closed without merging**
