### PR TITLE
chore: update links

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@sublimator, you probably saw the email from the W3C about joining the WICG for IPR purposes... when you get a few mins, please join. Thanks in advance!

**Comment by sublimator** [comment]
@marcoscaceres 
I clicked some things :) 
I think that's good?

**Comment by marcoscaceres** [comment]
All good! Thanks for clicking 😊 🐁

**Comment by sublimator** [comment]
yeeoo!

**Pull request merged**
