### PR TITLE
docs: updates to readme

### PR DESCRIPTION
**Pull request by melissahenderson**

### CODE REVIEW

**Comment by melissahenderson** [comment]
@huijing Do you mind giving this a look over when you're feeling better? I removed the "Web Monetization Specification" section and would like your opinion on whether that was a good idea. If not, I can add it back.

**Comment by huijing** [comment]
I think it's fine to remove, but could we keep those details in a separate MD file maybe?

**Comment by melissahenderson** [comment]
This merge will include fixes for #431

**Review by huijing — APPROVED** [review]
LGTM

**Pull request merged**
