### PR TITLE
Fix #85: Fixed size of gatsby logo

### LINKED ISSUE #85: Fix logo for Gatsby tool
The logo currently expands beyond the borders of the button.

cc @mrmuhammadali

### PR DESCRIPTION
**Pull request by mrmuhammadali**

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
@mrmuhammadali this still doesn't render for me on my local machine.
Screenshot 2020-06-24 at 16 37 00

**Comment by adrianhopebailie** [comment]
Chrome on OSX by the way

**Comment by mrmuhammadali** [comment]
> @mrmuhammadali this still doesn't render for me on my local machine.
> Screenshot 2020-06-24 at 16 37 00

Oops, the link to the image was broken. But fixed it now.

**Comment by adrianhopebailie** [comment]
@mrmuhammadali looks good. You need to sort out the [IPR contribution issue](https://labs.w3.org/repo-manager/pr/id/WICG/webmonetization/86) though

**Comment by mrmuhammadali** [comment]
How can pass last remaining check, do I need to request W3C account?

**Comment by dontcallmedom** [comment]
Marked as non substantive for IPR from ash-nazg.

**Pull request merged**
